# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "https://andreasm80.github.io/"  # Include trailing slash
#title = "From 0.985mhz... to several Ghz"  # Edit directly from config/_default/languages.toml # alternatively, uncomment this and remove `title` entry from the aforemention file.
copyright = "Myself"
#canonifyurls = true
paginate = 6
theme = ["github.com/chipzoller/hugo-clarity"]
disqusShortname = ""
enableEmoji = true

# Custom CSS
customCSS = ["sass/_override.sass"]

#TOC 
#[markup]
#  [markup.tableOfContents]
#    endLevel = 4
#    ordered = false
#    startLevel = 1

DefaultContentLanguage = "en"
# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[permalinks]
  post = '/:year/:month/:day/:title/'

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]
