
[en]
  title = "From 0.985mhz... to several Ghz"
  LanguageName = "English"
  weight = 1

#[no]
#  title = "Fra 0.985mhz... til maaange Ghz" # just for the sake of showing this is possible
#  LanguageName = "Norsk"
#  weight = 2
